### PR TITLE
Make self-contained library directory, choose platform at compile-time

### PR DESCRIPTION
**Pull request by dyoo**
This does most of the hard work loading the SDL libraries on the major platforms (x86 Windows, MacOSX, x86 Linux).

### CODE REVIEW

**Comment by pb82** [comment]
Your pull request ist merged and i can confirm it also works well with 
Linux_64. So now we are one step closer to a batteries-included SDL 
binding :) Maybe I add libSDL_image to the pre-packaged libs. Thanks 
again for your great work!

**Comment by dyoo** [comment]
On Fri, Jan 18, 2013 at 1:38 PM, Peter Braun notifications@github.comwrote:

> Your pull request ist merged and i can confirm it also works well with
> Linux_64. So now we are one step closer to a batteries-included SDL
> binding :) Maybe I add libSDL_image to the pre-packaged libs. Thanks
> again for your great work!
> 
> I did try to do libSDL_image, but the external requirements for the library
> are getting in the way; I haven't been able to resolve it yet.  SDL_image
> depends on libjpeg, libz, etc, and on linux, things just horribly broke on
> Linux.  I was able to get it working on MacOSX though.

I put the work on my sdl-image-load branch.

https://github.com/dyoo/sdl4racket/commit/36c91ac998116880a9d10018e420fc8350e32b13

but it definitely still needs work.

**Comment by dyoo** [comment]
> https://github.com/dyoo/sdl4racket/commit/36c91ac998116880a9d10018e420fc8350e32b13
> 
> but it definitely still needs work.

Just to let you know what I was thinking:

We can do without SDL_image if we integrate somehow with the bitmap%
stuff in Racket already.  After the SDL_image failure last night, I
spent the morning trying to figure out how to use the undocumented
Cairo bindings in racket/draw.  The idea is if we can get racket/draw
to run on an sdl context, we'd win.  :)

The cairo bindings in:

```
http://git.racket-lang.org/plt/tree/HEAD:/collects/racket/draw/unsafe
```

would need to be extended to support
cairo_image_surface_create_for_data, which we could create from an SDL
surface, following the instructions in:

```
http://www.cairographics.org/SDL/
```

It already has a binding to cairo_image_surface_create, so that part
should already be easy.

So if we do that, it shouldn't be too hard to make a "sdl_dc%" drawing
context, and then we're golden, since most anything else in
racket/draw only cares that it has a cairo_context, and not where the
context came from.

**Comment by pb82** [comment]
I've created a branch to try out integrating with bitmap%. I've added a function (load-image) which uses racket/draw's read-image instead of SDL_image's img-load and converts the bitmap% to a SDL_Surface. That's actually quite easy but hopefully there is a more efficient way to do it.

But i have yet to take a deeper look at racket/draw, and the bitmap% class.

**Pull request merged**
