### PR TITLE
Adding an example to show something move based on mouse movement.  Also ...

### PR DESCRIPTION
**Pull request by dyoo**
...exposed a bitmap->sdl-surface function.

Wanted a more interactive example just to show how to get things to "move".

### CODE REVIEW

**Comment by pb82** [comment]
Cool! Didn't know that .../null trick for ctypes ;)

**Comment by pb82** [comment]
I'm currently trying to get rid of all malloc calls (e.g. in 
sdl-get-rgb). My idea was to use a construct like

```
 (cvector-ptr (make-cvector _uint8 1))
```

instead of

```
 (malloc (ctype-sizeof _uint8))
```

This way we stay within the garbage collectors reach and thus no need to 
free it, right?
Or do I miss something here?

**Comment by dyoo** [comment]
On Wed, Jan 23, 2013 at 1:58 PM, Peter Braun notifications@github.comwrote:

> I'm currently trying to get rid of all malloc calls (e.g. in
> sdl-get-rgb). My idea was to use a construct like
> 
> (cvector-ptr (make-cvector _uint8 1))
> 
> instead of
> 
> (malloc (ctype-sizeof _uint8))
> 
> If I understand correctly, though, malloced memory should also be
> GC-friendly, unless we use the 'raw option.   For example, when I run:

;;;;;;;;;;;;;;;;;;;;;;;;;;;
#lang racket/base
(require ffi/unsafe)
(let loop ()
  (malloc 1000000)
  (loop))
;;;;;;;;;;;;;;;;;;;;;;;;;;;

I observe that the memory use of this is bounded because it's GCing.  If we
were to use 'raw, then I'd expect us to be in trouble.

**Comment by dyoo** [comment]
> > I'm currently trying to get rid of all malloc calls (e.g. in
> > sdl-get-rgb). My idea was to use a construct like
> > 
> > (cvector-ptr (make-cvector _uint8 1))
> > 
> > instead of
> > 
> > (malloc (ctype-sizeof _uint8))

I'm looking at this again.  I think I agree with you that doing the
make-cvector is a better idea that using malloc.

It turns out that if we use malloc with default settings, we're most
likely getting the behavior described by:

```
http://docs.racket-lang.org/inside/im_memoryalloc.html#(cpp._scheme_malloc)
```

which is almost certainly not what we want.  We don't want Racket to
treat the contents inside the allocated block as pointers!  :)  That
has the potential of making the GC very confused.  :)

**Comment by pb82** [comment]
Yes, the documentation says that malloc will fall back to 'nonatomic if 
no mode is provided. So either using malloc with explicit 'atomic mode 
or doing the make-cvector thing should work for us.

**Pull request merged**
